Controllers/UserPanelController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using WatchMNS.Database;
using WatchMNS.Models;
using WatchMNS.Services.Interfaces;
using WatchMNS.ViewModel;

namespace WatchMNS.Controllers
{
    [Authorize(Roles = "User")]
    public class UserPanelController : Controller
    {
        private DatabaseContext _dbContext = new DatabaseContext();
        private UserManager<Client> _userManager { get; set; }
        private readonly IClientService _clientService;
        private readonly ILateMissService _lateMissService;
        private readonly ILateMissStatusService _lateMissStatusService;

        public UserPanelController(UserManager<Client> userManager,IClientService clientService, ILateMissService lateMissService, ILateMissStatusService lateMissStatusService)
        {
            _userManager = userManager;
            _lateMissService = lateMissService;
            _lateMissStatusService = lateMissStatusService;
            _clientService = clientService;
        }
        public IActionResult Panel()
        {
            string? clientId = User
                .FindFirstValue(ClaimTypes.NameIdentifier);

            Client? client = _dbContext.Client
                .Where(x => x.Id == clientId)
                .FirstOrDefault();

            return View(client);
        }

        public async Task<IActionResult> DelayManager()
        {
            string? clientId = User
                .FindFirstValue(ClaimTypes.NameIdentifier);

            if (clientId == null)
            {
                return new ContentResult { Content = "User does not exist.", ContentType = "text/plain", StatusCode = 400 };
            }

            Client? client = await _clientService.GetByIdAsync(clientId);

            List<LateMiss> existingLateMisses = await _lateMissService.GetLateMissesFromUser(client, "Retard");

            var viewModel = new DelayDeclarationViewModel
            {
                ExistingLateMisses = existingLateMisses,
                NewLateMiss = new()
            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> DelayManager(DelayDeclarationViewModel viewModel)
        {
            string? clientId = User
                .FindFirstValue(ClaimTypes.NameIdentifier);

            if (clientId == null)
            {
                return new ContentResult { Content = "User does not exist.", ContentType = "text/plain", StatusCode = 400 };
            }

            Client? client = await _clientService.GetByIdAsync(clientId);

            viewModel.NewLateMiss.Client = client;
            viewModel.NewLateMiss.DeclarationDate = DateTime.Now.Date;
            viewModel.NewLateMiss.LateMissType = "Retard";
            viewModel.NewLateMiss.StartDate = DateTime.Today.AddHours(8);
            viewModel.NewLateMiss.lateMissStatus = _dbContext.LateMissStatus
                .Where(lms => lms.Label == "En Attente")
                .FirstOrDefault();
            

            var existingLateMisses = _dbContext.LateMiss
                .Where(x => (x.Client == client) && (x.LateMissType == "Retard"))
                .Include(x => x.lateMissStatus)
                .ToList();

            viewModel.ExistingLateMisses = existingLateMisses;

            //if (!ModelState.IsValid)
            //{
            //    return View(viewModel);
            //}
            
            _dbContext.LateMiss.Add(viewModel.NewLateMiss);
            _dbContext.SaveChanges();

            return RedirectToAction("DelayManager");
        }

        public IActionResult AbsenceManager()
        {
            string? clientId = User
                .FindFirstValue(ClaimTypes.NameIdentifier);

            Client? client = _dbContext.Client
                .FirstOrDefault(x => x.Id == clientId);

            if (client == null)
            {
                return NotFound();
            }

            var existingLateMisses = _dbContext.LateMiss
                .Where(x => (x.Client == client) && (x.LateMissType == "Absence"))
                .Include(x => x.lateMissStatus)
                .ToList();

            var newLateMiss = new LateMiss();

            var viewModel = new AbsenceDeclarationViewModel
            {
                ExistingLateMisses = existingLateMisses,
                NewLateMiss = newLateMiss
            };

            return View(viewModel);
        }


        [HttpPost]
        public IActionResult AbsenceManager(AbsenceDeclarationViewModel viewModel)
        {
            string? clientId = User
                .FindFirstValue(ClaimTypes.NameIdentifier);

            Client? client = _dbContext.Client
                .FirstOrDefault(x => x.Id == clientId);

            viewModel.NewLateMiss.Client = client;
            viewModel.NewLateMiss.DeclarationDate = DateTime.Now.Date;
            viewModel.NewLateMiss.LateMissType = "Absence";
            viewModel.NewLateMiss.StartDate = DateTime.Today.AddHours(8);
            viewModel.NewLateMiss.lateMissStatus = _dbContext.LateMissStatus
                .Where(lms => lms.Label == "En Attente")
                .FirstOrDefault();


            var existingLateMisses = _dbContext.LateMiss
                .Where(x => (x.Client == client) && (x.LateMissType == "Absence"))
                .Include(x => x.lateMissStatus)
                .ToList();

            viewModel.ExistingLateMisses = existingLateMisses;

            //if (!ModelState.IsValid)
            //{
            //    return View(viewModel);
            //}

            _dbContext.LateMiss.Add(viewModel.NewLateMiss);
            _dbContext.SaveChanges();

            return RedirectToAction("AbsenceManager");
        }
    }
}

Views/UserPanel/AbsenceManager.cshtml
@using System.Security.Claims
@model WatchMNS.ViewModel.AbsenceDeclarationViewModel

<div class="container-fluid custom-border mb-3 p-3 mt-3 text-light">
    <h1 class="text-center">Vos absences : </h1>

    @if (Model.ExistingLateMisses.Count > 0)
    {
        @foreach (var delay in Model.ExistingLateMisses)
        {
            <div class="custom-border mt-3 p-3">
                <h3 class="text-decoration-underline">Absence</h3>
                <p><span class="fw-bold">Date de déclaration :</span> @delay.DeclarationDate</p>
                <p><span class="fw-bold">Statut de validation :</span> @delay.lateMissStatus.Label</p>
                <p><span class="fw-bold">Motif :</span> @delay.Reason</p>
            </div>
        }
    }
    else
    {
        <p>Aucune absence à signaler.</p>
    }

</div>

<div class="custom-border bg-dark bg-opacity-50 text-light p-3">
    <h1 class="text-center">Déclarer une absence : </h1>
    <form method="post">
        <div class="text-danger" asp-validation-summary="All"></div>
        <div class="form-sizing col-md-6">
            <input type="hidden" asp-for="NewLateMiss.LateMissType" value="Absence">
            <input type="hidden" asp-for="NewLateMiss.Client.Id" value="@User.FindFirstValue(ClaimTypes.NameIdentifier)">
            <div class="mb-3">
                <label for="Reason" class="form-label text-light">Motif</label>
                <input class="form-control" type="text" asp-for="NewLateMiss.Reason">
                <span asp-validation-for="NewLateMiss.Reason" class="text-danger"></span>
            </div>
            @* <div class="mb-3">
            <label for="Document" class="form-label text-light">Image</label>
            <input class="form-control" type="image">
            </div> *@
            <p class="text-center">Votre déclaration sera soumise à une validation administrative.</p>
            <div class="col-auto text-center mt-3">
                <a class="btn btn-dark border-2 custom-border mt-3 mb-2 me-2 col-6 col-md-2" asp-controller="UserPanel" asp-action="Panel">Retour</a>
                <button type="submit" class="btn btn-dark border-2 custom-border mt-3 mb-2 me-2 col-6 col-md-2">Déclarer</button>
            </div>
        </div>
    </form>
</div>

Views/UserPanel/DelayManager.cshtml
@using System.Security.Claims
@model WatchMNS.ViewModel.DelayDeclarationViewModel

<div class="container-fluid custom-border mb-3 p-3 mt-3 text-light">
    <h1 class="text-center">Vos retards : </h1>

    @if(Model.ExistingLateMisses.Count > 0)
    {
        @foreach (var delay in Model.ExistingLateMisses)
        {
            <div class="custom-border mt-3 p-3">
                <h3 class="text-decoration-underline">Retard</h3>
                <p><span class="fw-bold">Date de déclaration :</span> @delay.DeclarationDate.ToShortDateString()</p>
                <p><span class="fw-bold">Statut de validation :</span> @delay.lateMissStatus.Label</p>
                <p><span class="fw-bold">Motif :</span> @delay.Reason</p>
            </div>
        }
    }
    else
    {
        <p>Aucun retard à signaler.</p>
    }

</div>

<div class="custom-border bg-dark bg-opacity-50 text-light p-3">
    <h1 class="text-center">Déclarer un retard : </h1>
    <form method="post">
        <div class="text-danger" asp-validation-summary="All"></div>
        <div class="form-sizing col-md-6">
            <input type="hidden" asp-for="NewLateMiss.LateMissType" value="Retard">
            <input type="hidden" asp-for="NewLateMiss.Client.Id" value="@User.FindFirstValue(ClaimTypes.NameIdentifier)">
            <div class="mb-3">
                <label for="Reason" class="form-label text-light">Motif</label>
                <input class="form-control" type="text" asp-for="NewLateMiss.Reason">
                <span asp-validation-for="NewLateMiss.Reason" class="text-danger"></span>
            </div>
            @* <div class="mb-3">
                <label for="Document" class="form-label text-light">Image</label>
                <input class="form-control" type="image">
            </div> *@
            <p class="text-center">Votre déclaration sera soumise à une validation administrative.</p>
            <div class="col-auto text-center mt-3">
                <a class="btn btn-dark border-2 custom-border mt-3 mb-2 me-2 col-6 col-md-2" asp-controller="UserPanel" asp-action="Panel">Retour</a>
                <button type="submit" class="btn btn-dark border-2 custom-border mt-3 mb-2 me-2 col-6 col-md-2">Déclarer</button>
            </div>
        </div>
    </form>
</div>

Views/UserPanel/Panel.cshtml
@model WatchMNS.Models.Client

<h1 class="text-light">@Model.Lastname @Model.Firstname</h1>

<div class="col-12 custom-border-5 d-lg-flex justify-content-between p-4">
    <div class="col-12 col-lg-2 custom-border d-flex flex-column justify-content-center align-items-center">
        <a class="btn btn-dark border-2 custom-border col-10 col-md-10 mt-3" asp-controller="ManageAccount" asp-action="EditUser">Editer mon profil</a>
        <a class="btn btn-dark border-2 custom-border col-10 col-md-10 mt-3" asp-controller="UserPanel" asp-action="AbsenceManager">Gestion d'absence</a>
        <a class="btn btn-dark border-2 custom-border col-10 col-md-10 mt-3" asp-controller="UserPanel" asp-action="DelayManager">Gestion de retard</a>
        <a class="btn btn-dark border-2 custom-border col-10 col-md-10 mt-3" asp-controller="User" asp-action="DocumentManager">Gestion de Document</a>
        <a class="btn btn-dark border-2 custom-border col-10 col-md-10 mt-3" asp-controller="ManageAccount" asp-action="EditUser">Consulter sa formation</a>
        <a class="btn btn-dark border-2 custom-border col-10 col-md-10 mt-3 mb-3" asp-controller="ManageAccount" asp-action="EditUser">Editer mon profil</a>
    </div>
    <div class="col-12 col-lg-10 custom-border d-flex flex-column justify-content-center align-items-center text-light">
        <h1>Graphic</h1>
    </div>
</div>