Controllers/ManageAccountController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using WatchMNS.Database;
using WatchMNS.Models;
using WatchMNS.ViewModel;

namespace WatchMNS.Controllers
{
    [Authorize]
    public class ManageAccountController : Controller
    {
        private DatabaseContext _dbContext = new DatabaseContext();
        private UserManager<Client> _userManager { get; set; }

        public ManageAccountController(UserManager<Client> userManager)
        {
            _userManager = userManager;
        }
        public IActionResult EditUser()
        {
            string id = User
                .FindFirstValue(ClaimTypes.NameIdentifier);

            Client? client = _dbContext.Client
                .Where(x => x.Id == id)
                .FirstOrDefault();

            List<ProfessionnalStatus> professionnalStatusesList = _dbContext.ProfessionnalStatus
                .ToList();


            UserEditUserViewModel viewModel = new UserEditUserViewModel();
            viewModel.Id = id;
            viewModel.Lastname = client.Lastname;
            viewModel.Firstname = client.Firstname;
            viewModel.Email = client.Email;
            viewModel.Address = client.Address;
            viewModel.City = client.City;
            viewModel.PostCode = client.PostCode;
            viewModel.Country = client.Country;
            viewModel.PhoneNumber = client.PhoneNumber;
            viewModel.NativeCity = client.NativeCity;
            viewModel.NativeCountry = client.NativeCountry;
            viewModel.ProfessionnalStatusId = client.ProfessionnalStatusId;
            viewModel.professionnalStatuses = professionnalStatusesList;

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult EditUser(UserEditUserViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                foreach (string key in ModelState.Keys)
                {
                    ModelError? error = ModelState[key].Errors.FirstOrDefault();
                    if (error != null)
                    {
                        Console.WriteLine(error.ErrorMessage);
                    }
                }
                return View(viewModel);
            }

            Client? client = _dbContext.Client
                .Where(x => x.Id == viewModel.Id)
                .FirstOrDefault();

            client.Lastname = viewModel.Lastname;
            client.Firstname = viewModel.Firstname;
            client.Email = viewModel.Email;
            client.Address = viewModel.Address;
            client.City = viewModel.City;
            client.PostCode = viewModel.PostCode;
            client.Country = viewModel.Country;
            client.BirthDate = viewModel.BirthDate;
            client.PhoneNumber = viewModel.PhoneNumber;
            client.NativeCity = viewModel.NativeCity;
            client.NativeCountry = viewModel.NativeCountry;
            client.ProfessionnalStatusId = viewModel.ProfessionnalStatusId;

            _dbContext.Client.Update(client);
            _dbContext.SaveChanges();

            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> DisplayUser()
        {
            string? id = User
                .FindFirstValue(ClaimTypes.NameIdentifier);

            Client? client = _dbContext.Client
                .Where(x => x.Id == id)
                .FirstOrDefault();

            var clientRoles = await _userManager
                .GetRolesAsync(client);

            var clientProStatus = _dbContext.ProfessionnalStatus
                .Where(x => x.Id == client.ProfessionnalStatusId)
                .FirstOrDefault();

            int totalAbsence = _dbContext.LateMiss
                .Where(lm => lm.LateMissType == "Absence" && lm.Client.Id == client.Id)
                .ToList()
                .Count();

            int totalDelay = _dbContext.LateMiss
                .Where(lm => lm.LateMissType == "Retard" && lm.Client.Id == client.Id)
                .ToList()
                .Count();

            float absencePercentage = (float) (totalAbsence * 100) / 218;
            float delayPercentage = (float) (totalDelay * 100) / 218;

            DisplayUserViewModel viewModel = new DisplayUserViewModel();

            viewModel.Id = id;
            viewModel.Lastname = client.Lastname;
            viewModel.Firstname = client.Firstname;
            viewModel.Email = client.Email;
            viewModel.Address = client.Address;
            viewModel.City = client.City;
            viewModel.PostCode = client.PostCode;
            viewModel.Country = client.Country;
            viewModel.PhoneNumber = client.PhoneNumber;
            viewModel.NativeCity = client.NativeCity;
            viewModel.NativeCountry = client.NativeCountry;
            viewModel.Role = clientRoles;
            viewModel.TotalAbsence = totalAbsence;
            viewModel.TotalDelay = totalDelay;
            viewModel.AbsencePercentage = (float) Math.Round(absencePercentage, 2);
            viewModel.DelayPercentage = (float) Math.Round(delayPercentage, 2);

            if (clientProStatus != null)
                viewModel.ProfessionnalStatusLabel = clientProStatus.Label;
            else
                viewModel.ProfessionnalStatusLabel = "Aucun";

            return View(viewModel);
        }
    }
}

Views/ManageAccount/DisplayUser.cshtml
@using WatchMNS.Database
@model WatchMNS.ViewModel.DisplayUserViewModel

<div class="mt-5 mb-5 p-5 custom-border-5">
    <h1 class="text-light text-center mb-5 fw-bolder">Votre profil</h1>
    <div class="card bg-black bg-opacity-50 custom-border-5 mx-auto mt-3 col-8">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="~/images/missing-pp.jpg" class="img-fluid rounded-start" alt="Profile picture">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title fw-bolder text-decoration-underline text-light">@Model.Lastname @Model.Firstname</h5>
                    <h6 class="card-title text-light">@Model.Email</h6>
                    <h6 class="card-title text-light">@Model.PhoneNumber</h6>
                    <h6 class="card-title text-light">@Model.Address</h6>
                    <h6 class="card-title text-light">@Model.City - @Model.PostCode</h6>
                    @foreach(var role in Model.Role)
                    {
                        <h6 class ="card-title text-light">Role : @role</h6>
                    }
                    <h6 class="card-title text-light">Pro. Status : @Model.ProfessionnalStatusLabel</h6>
                </div>
            </div>
        </div>
    </div>
    <div class="text-center">
        <a class="btn col-8 btn-dark border-1 custom-border" asp-controller="ManageAccount" asp-action="EditUser">Editer</a>
    </div>
    <div class="col-8 bg-black bg-opacity-50 mx-auto  mt-5 custom-border-5">
        <div class="row d-flex justify-content-evenly">
            <div class="mb-3 bg-transparent pt-4 col-4">
                <p class="text-light">Absence(s) : @Model.TotalAbsence</p>
                <p class="text-light">Retard(s) : @Model.TotalDelay</p>
            </div>
            <div class="bg-transparent pt-4 col-4">
                <p class="text-light">% Jours Absent : @Model.AbsencePercentage%</p>
                <p class="text-light">% Jours Retard : @Model.DelayPercentage%</p>
            </div>
        </div>
    </div>
    
</div>

Views/ManageAccount/EditUser.cshtml
@model WatchMNS.ViewModel.UserEditUserViewModel


<div class="row">
    <div class="p-3 mt-3 custom-border-5 rounded">
        <form asp-action="EditUser">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <h2 class="text-light text-center">Editer informations de : @Model.Firstname @Model.Lastname</h2>
            <br />
            <div class="row">
                <div class="col-12 col-md-8 col-lg-4 mt-3 mx-auto ">
                    <div class="p-3 custom-border rounded">
                        <div class="form-group">
                            <label asp-for="Firstname" class="control-label text-light mt-3">Prénom</label>
                            <input asp-for="Firstname" class="form-control" />
                            <span asp-validation-for="Firstname" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Lastname" class="control-label text-light mt-3">Nom de famille</label>
                            <input asp-for="Lastname" class="form-control" />
                            <span asp-validation-for="Lastname" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Email" class="control-label text-light mt-3">Adresse mail</label>
                            <input asp-for="Email" class="form-control" />
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Address" class="control-label text-light mt-3">Adresse</label>
                            <input asp-for="Address" class="form-control" />
                            <span asp-validation-for="Address" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="PostCode" class="control-label text-light mt-3">Code Postal</label>
                            <input asp-for="PostCode" class="form-control" />
                            <span asp-validation-for="PostCode" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="City" class="control-label text-light mt-3">Ville</label>
                            <input asp-for="City" class="form-control" />
                            <span asp-validation-for="City" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-md-8 col-lg-4 mt-3 mx-auto">
                    <div class="p-3 custom-border rounded">
                        <div class="form-group">
                            <label asp-for="Country" class="control-label text-light mt-3">Pays</label>
                            <input asp-for="Country" class="form-control" />
                            <span asp-validation-for="Country" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="BirthDate" class="control-label text-light mt-3">Date de naissance</label>
                            <input asp-for="BirthDate" class="form-control" />
                            <span asp-validation-for="BirthDate" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="PhoneNumber" class="control-label text-light mt-3">Numéro de téléphone</label>
                            <input asp-for="PhoneNumber" class="form-control" />
                            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="NativeCity" class="control-label text-light mt-3">Ville de naissance</label>
                            <input asp-for="NativeCity" class="form-control" />
                            <span asp-validation-for="NativeCity" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="NativeCountry" class="control-label text-light mt-3">Pays de naissance</label>
                            <input asp-for="NativeCountry" class="form-control" />
                            <span asp-validation-for="NativeCountry" class="text-danger"></span>
                        </div>

                        <label asp-for="ProfessionnalStatusId" class="control-label text-light mt-3">Status professionnel</label>
                        <select class="form-select" asp-for="@Model.ProfessionnalStatusId">
                            @foreach (ProfessionnalStatus professionnalStatus in Model.professionnalStatuses)
                            {
                                <option value='@professionnalStatus.Id'>@professionnalStatus.Label</option>
                            }
                        </select>
                    </div>
                </div>
            </div>
            <div class="form-group d-flex justify-content-center">
                <a class="btn btn-dark border-2 custom-border mt-5 mb-2 me-2 col-6 col-md-auto" asp-controller="ManageAccount" asp-action="DisplayUser">Retour</a>
                <input type="submit" value="Envoyer" class="btn btn-dark border-2 custom-border mt-5 mb-2 col-6 col-md-auto" />
            </div>
        </form>
    </div>
</div>